### ISSUE TITLE
Notification sticks indefinitly

### ISSUE THREAD

**Issue by ArunKumar28** [naman14/TimberX#32] opened 2019-02-07 06:25 UTC
Add removable notification on stopped music file

**Comment by afollestad** [comment] 2019-02-07 06:28
I believe this is a duplicate of https://github.com/naman14/TimberX/issues/30.

**Closed by afollestad** 2019-02-07 06:28 UTC

**Comment by ArunKumar28** [comment] 2019-02-07 06:36
But i have updated playstore app installed,there is no cross button

**Comment by afollestad** [comment] 2019-02-07 06:37
This has not been implemented yet. The linked issue is still open.

**Comment by ArunKumar28** [comment] 2019-02-07 06:38
Ok

**Comment by naman14** [comment] 2019-02-07 06:44
Will do this in next release
